pub mod ai;
pub mod config;
pub mod crypto;
pub mod crud;
pub mod db;
pub mod error;
pub mod knowledge_base;
pub mod loadgen;
pub mod navicat;
pub mod perf_report;
pub mod rule_engine;
pub mod rule_matcher;
pub mod schema;
pub mod service;
pub mod sql;
pub mod sync;
pub mod timeout_policy;
pub mod tools;

// Backward-compatible re-exports for moved modules
pub use db::capability as db_capability;
pub use db::protocol as db_protocol;
pub use db::pg_adapter;
pub use db::sqlite_adapter;
pub use schema::ext as schema_ext;
pub use sql::history as sql_history;
pub use sql::offline_parser;
pub use sql::template as template;
pub use sql::util as sql_util;
pub use sync::mysql_engine as mysql_sync;
pub use sync::mysql_engine as data_sync;
pub use sync::transfer;
