name: Mirror to Gitee

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts
      - run: |
          git remote add gitee git@gitee.com:zhu_ming_chen/rust-local-sql-tool.git
          git push gitee --mirror
